### ISSUE TITLE
Does not work with database containing unicode data.

### ISSUE THREAD

**Issue by simonvc** [gianlucaborello/cassandradump#1]
```
Traceback (most recent call last):
  File "cassandradump.py", line 247, in <module>
    main()
  File "cassandradump.py", line 241, in main
    export_data(session)
  File "cassandradump.py", line 142, in export_data
    table_to_cqlfile(session, keyname, tablename, None, tableval, f)
  File "cassandradump.py", line 44, in table_to_cqlfile
    filep.write('INSERT INTO "' + keyspace + '"."' + tablename + '" (' + ', '.join(row.keys()) + ') VALUES (' + ', '.join(values) + ')\n')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 206: ordinal not in range(128)
```

**Comment by gianlucaborello** [comment]
Thanks for the report.

Can you please try again now? It works in my case (tried with a couple random unicode characters in a text/varchar column, I don't have a massive database using those types).

**Comment by CleytonBonamigo** [comment]
Not the same, but similar error, on the same line:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 42: ordinal not in range(128)

Have any idea?

**Comment by gianlucaborello** [comment]
Do you have by any chance a snippet of data (e.g. a INSERT query along with the CREATE table) that can reproduce the issue? I thought I fixed it a few weeks ago.

**Comment by CleytonBonamigo** [comment]
Well, the string that's trying to export have some special chars, like '~, ^, etc'. 
The exact word is 'Bebê'.

**Comment by gianlucaborello** [comment]
Please give it another try and let me know, I've done another fix.

**Comment by CleytonBonamigo** [comment]
Worked well, thanks @gianlucaborello

**Comment by gianlucaborello** [comment]
Great
