### ISSUE TITLE
Exception on import large database

### ISSUE THREAD

**Issue by CleytonBonamigo** [gianlucaborello/cassandradump#4]
Hello, when I tried to import a large database, 600k+ lines, throwed me an exception:

> Traceback (most recent call last):
>  File "../cassandradump/cassandradump.py", line 271, in <module>
>    main()
>  File "../cassandradump/cassandradump.py", line 263, in main
>    import_data(session)
>  File "../cassandradump/cassandradump.py", line 65, in import_data
>    session.execute(line)
>  File "/usr/local/lib/python2.7/dist-packages/cassandra/cluster.py", line 1405, in execute
>    result = future.result(timeout)
>  File "/usr/local/lib/python2.7/dist-packages/cassandra/cluster.py", line 2976, in result
>    raise self._final_exception
> cassandra.protocol.SyntaxException: <ErrorMessage code=2000 [Syntax error in CQL query] >message="line 0:-1 no viable alternative at input '<EOF>'">

Script imported most of the code, but the last table, with 500k lines, imported only 11k.

Thanks any way.

**Comment by gianlucaborello** [comment]
It seems like the script generated a statement which is invalid, hence the syntax exception.

Would you be able to narrow down the issue? You could for example print each statement while it gets imported, or just copy and paste some random data until you get the faulty one. That way I would be able to fix it.
