### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by zaibacu** [gianlucaborello/cassandradump#6]
File "cassandradump.py", line 63
    for has_counter, columns in itertools.groupby(tableval.columns.iteritems(), lambda (k, v): v.data_type.typename == 'counter')
                                                                                       ^
SyntaxError: invalid syntax

**Comment by zaibacu** [comment]
Only on Python3.\* version

**Comment by jpatel956** [comment]
@zaibacu , have you got solution for this syntex error? I have same problem.

**Comment by zaibacu** [comment]
quickfix would be: 
```
lambda (k, v): v.data_type.typename == 'counter'
```

->

```
lambda x: x[1].data_type.typename == 'counter'
```

Maybe I will do PR if will not forget, issue seems to be a bit old

**Comment by jpatel956** [comment]
@zaibacu 

It would be batter if you provide "cassandradump.py" file after updating as "k" and "v" variable used at some other place as well. 

Thanks

**Comment by jpatel956** [comment]
@zaibacu 

after replacing you code and executing following command.

python cassandradump.py --keyspace ABC  --import-file sqldump.mysql

Got the following error:

<codecs.StreamReaderWriter object at 0x10f320278>
Traceback (most recent call last):
  File "cassandradump.py", line 406, in <module>
    main()
  File "cassandradump.py", line 398, in main
    import_data(session)
  File "cassandradump.py", line 152, in import_data
    session.execute(statement)
  File "cassandra/cluster.py", line 2171, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4062, in cassandra.cluster.ResponseFuture.result
cassandra.protocol.SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:64 no viable alternative at input ';' (/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */[;])">


Can you please help me out?

Thanks

**Comment by zaibacu** [comment]
Well this error is kinda unrelated, and more like a problem with this project itself. 

However, at first glance - it looks that you're trying to import MySQL file to Cassandra? Cassandra uses CQL. CQL is mostly similar, but there are some syntax differences which makes it incompatible

**Comment by jpatel956** [comment]
@zaibacu 

Thanks for your time. as this repository mention, You can import/export data from cassandra so i am tring exact things. however have you ever tried to dump all mysql database to cassandra ? 

Thanks

**Comment by gianlucaborello** [comment]
I'm closing this one since I just merged the relative PR. @jpatel956 the goal of this project is not to make it compatible with MySQL, it's just to have a quick and easy way to dump Cassandra data **as if** it was the mysqldump tool, but MySQL doesn't really enter into the picture here.

Thanks
